language: csharp
solution: ./fluent-api.sln
install:
  - nuget restore ./fluent-api.sln
  - nuget install NUnit.ConsoleRunner -Version 3.9.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release ./fluent-api.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./ObjectPrinterTests/bin/Release/ObjectPrinterTests.dll
